### PR TITLE
First milestone

### PR DESCRIPTION
**Pull request by Abdusaid10**
- Initialized project
- removed unnecessary files
- added big.js & prop-types
- deployed to Heroku
- set up eslint & stickler

### CODE REVIEW

**Review by Forison — CHANGES_REQUESTED** [review]
## Status:: Changes Required❌
# 🙋‍♂️ Abdusaid
Good job done so far, however here are few issues to address to get this project approved.
I am unable to see the packages ie, big.js and prop-type in the your ```package.json``` on ```first-milestone branch```. Kindly use ```npm``` to install it.
* [ ] big.js added to package.json ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/calculator/milestone1/big.png) from [pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/44896085/))
* [ ] [`prop-types`](https://www.npmjs.com/package/prop-types) added to package.json for [typechecking props](https://reactjs.org/docs/typechecking-with-proptypes.html) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/section/propTypes.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/44896085/))
here is an image of your current package.json of the ```first-milestone branch```
oneee
onee

* [ ] Linters config: Do not make any changes in config files - they represent style guidelines that you share with your team - which is a group of all Microverse students. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/linter_config.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/54883773/))

### That is it, kindly make the changes and submit another re-review👨‍✈️.
#### Happy coding👨‍💻 
Addo Forison

**Review by fatymahmed — CHANGES_REQUESTED** [review]
## Hi @Abdusaid10 👋
Great job adding the packages as requested in the previous review 👏👏, however, there's one more thing that we need to fix.
- [ ] There are no linter checks so let's fix that, follow [these](https://github.com/microverseinc/linters-config/tree/master/html-css) instructions to setup linter

[OPTIONAL]
- Update your readme file with relevant information about your project see [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_readme.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/)
## Status: Changes Required ♻️
_Feel free to reach out to me on slack (Fatima) if you have any questions or need any help 🙂_

**Comment by Abdusaid10** [comment]
I added linters.yml as you can see. But it's not working for this branch, don't know the reason. However, it is working for the second milestone, you can check that [here](https://github.com/Abdusaid10/calculator-app/pull/4)

**Review by suretrust — APPROVED** [review]
Hi @Abdusaid10, 👋 

### Great job implementing the suggested changes. 🙌 Let's get this merged! 👍 

_Good luck with your future milestones and happy coding!_ 🎉

**Pull request merged**
